// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project04_ShopApp.Data;

#nullable disable

namespace Project04_ShopApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260107204429_EditedProductEntity")]
    partial class EditedProductEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Project04_ShopApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Bilgisayar",
                            Description = "Yüksek performanslı laptop",
                            Name = "Laptop Pro",
                            Price = 1299.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Bilgisayar",
                            Description = "Oyuncular için gelişmiş laptop",
                            Name = "Gaming Laptop",
                            Price = 1599.99m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 3,
                            Category = "Bilgisayar",
                            Description = "Taşınabilir ve hafif ultrabook",
                            Name = "Ultrabook",
                            Price = 999.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 4,
                            Category = "Telefon",
                            Description = "Amiral gemisi akıllı telefon",
                            Name = "Smartphone X",
                            Price = 899.99m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 5,
                            Category = "Telefon",
                            Description = "Uygun fiyatlı akıllı telefon",
                            Name = "Smartphone Lite",
                            Price = 499.99m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 6,
                            Category = "Bilgisayar Ürünleri",
                            Description = "RGB mekanik klavye",
                            Name = "Mechanical Keyboard",
                            Price = 129.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 7,
                            Category = "Bilgisayar Ürünleri",
                            Description = "Yüksek hassasiyetli oyuncu faresi",
                            Name = "Gaming Mouse",
                            Price = 59.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 8,
                            Category = "Bilgisayar Ürünleri",
                            Description = "27 inç 4K monitör",
                            Name = "4K Monitor",
                            Price = 349.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 9,
                            Category = "Bilgisayar Ürünleri",
                            Description = "1080p çözünürlüklü webcam",
                            Name = "Webcam HD",
                            Price = 49.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 10,
                            Category = "Bilgisayar Ürünleri",
                            Description = "Çok amaçlı bağlantı istasyonu",
                            Name = "USB-C Dock",
                            Price = 79.99m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 11,
                            Category = "Bilgisayar Ürünleri",
                            Description = "1TB hızlı taşınabilir SSD",
                            Name = "External SSD",
                            Price = 149.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 12,
                            Category = "Bilgisayar Ürünleri",
                            Description = "DDR4 3200MHz RAM",
                            Name = "RAM 16GB",
                            Price = 69.99m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 13,
                            Category = "Bilgisayar Ürünleri",
                            Description = "Sessiz işlemci soğutucusu",
                            Name = "CPU Cooler",
                            Price = 39.99m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 14,
                            Category = "Bilgisayar Ürünleri",
                            Description = "650W 80+ Bronze güç kaynağı",
                            Name = "Power Supply 650W",
                            Price = 89.99m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 15,
                            Category = "Bilgisayar Ürünleri",
                            Description = "ATX oyuncu kasası",
                            Name = "PC Case",
                            Price = 99.99m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 16,
                            Category = "Aksesuar",
                            Description = "Taşınabilir bluetooth hoparlör",
                            Name = "Bluetooth Speaker",
                            Price = 39.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 17,
                            Category = "Aksesuar",
                            Description = "Yüksek kapasiteli powerbank",
                            Name = "Powerbank 20.000mAh",
                            Price = 29.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 18,
                            Category = "Aksesuar",
                            Description = "Hızlı şarj kablosu",
                            Name = "Charging Cable",
                            Price = 9.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 19,
                            Category = "Aksesuar",
                            Description = "Kablosuz hızlı şarj cihazı",
                            Name = "Wireless Charger",
                            Price = 24.99m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 20,
                            Category = "Aksesuar",
                            Description = "Ayarlanabilir telefon standı",
                            Name = "Phone Stand",
                            Price = 14.99m,
                            Stock = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
