# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copy the csproj file and load the dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the other files and compile them.
COPY . ./
RUN dotnet build -c Release -o /app/build

# Publish stage
FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

# Runtime Stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

# Yayınlanan dosyaları yayınlama aşamasından çalışma zamanı aşamasına kopyala
COPY --from=publish /app/publish .

# port
EXPOSE 8080

# Environment Variables
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production

# Run the application
ENTRYPOINT [ "dotnet", "EShopApp.dll" ]